# %% [markdown]
"""
In this example we will read in files to a TerraModel show how to plot a 1D profile.
First we will import all of the necessary python objects.
"""
# %%

from terratools.example_data import example_terra_layer
from terratools.terra_model import read_netcdf
import os
import matplotlib.pyplot as plt


# %% [markdown]
"""
Now let's download and read in the example mantle convection model netcdf file
 and print some summary information.
"""
# %%

# Read in the netcdf files.
# Download and cache model
path = example_terra_layer()

# %% [markdown]
"""
We can now read the example data into a TerraModelLayer object. Note that this uses the
same `read_netcdf` method as if we were reading a whole 3D model, terratools recognises
that this is a single layer and loads it as a layer object. The example layer provided
is a concatenation of the files generated by each process of a simulation. To read a
concatenated file we pass in the `cat=True` argument to `read_netcdf()`.
A
"""
# %%

layer = read_netcdf(path, cat=True)

# %% [markdown]
"""
We can check which fields are present in the TerraModelLayer.
"""
# %%

print(layer.field_names())

# %% [markdown]
"""
As a single layer, the `get_radii()` method should return only a single value.
"""
# %%

print(len(layer.get_radii()))

# %% [markdown]
"""
And we can plot a map of a field in the same way we would plot a layer of a TerraModel.
"""
# %%

layer.plot_layer("sigma_z", 0)
plt.show()
